/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZR_AFF_PROPAG_DEMANDEListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iCheckFilterField("NumTransaction");
            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iCheckFilterField("ElementOTP");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iCheckColumns(undefined, {"NumTransaction":{"header":"N° Document"},"Libelle":{"header":"Désignation"},"ElementOTP":{"header":"Élément OTP"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iCheckRows();

            When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iPressRow(0);
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});