/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZR_AFF_PROPAG_DEMANDEObjectPageObjectPage journey");

        opaTest("Navigate to ZR_AFF_PROPAG_DEMANDEObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iCheckRows();
            When.onTheZR_AFF_PROPAG_DEMANDEListGenerated.onTable().iPressRow(0);

            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "NumTransaction" });
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Libelle" });
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TypeProcessus" });
            Then.onTheZR_AFF_PROPAG_DEMANDEObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ElementOTP" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});